package jbLPC.scanner;

public enum TokenType {
  // Single-character tokens.
  TOKEN_LEFT_PAREN, TOKEN_RIGHT_PAREN,
  TOKEN_LEFT_BRACE, TOKEN_RIGHT_BRACE,
  TOKEN_COMMA, TOKEN_DOT, TOKEN_PLUS,
  TOKEN_SEMICOLON, TOKEN_SLASH, TOKEN_STAR,

  // One or two character tokens.
  TOKEN_BANG, TOKEN_BANG_EQUAL,
  TOKEN_EQUAL, TOKEN_EQUAL_EQUAL,
  TOKEN_GREATER, TOKEN_GREATER_EQUAL,
  TOKEN_INVOKE, TOKEN_LESS, TOKEN_LESS_EQUAL,
  TOKEN_MINUS,

  // Two character tokens
  TOKEN_DBL_AMP, TOKEN_DBL_PIPE,

  // Literals.
  TOKEN_IDENTIFIER, TOKEN_STRING, TOKEN_NUMBER,

  // Keywords.
  TOKEN_ELSE, TOKEN_FALSE,
  TOKEN_FOR, TOKEN_IF, TOKEN_NIL,
  TOKEN_RETURN, TOKEN_SUPER, TOKEN_THIS,
  TOKEN_TRUE, TOKEN_WHILE,

  // Type tokens.
  TOKEN_T_INT, TOKEN_T_OBJECT, TOKEN_T_STATUS, TOKEN_T_STRING,
  TOKEN_T_VOID,

  // Special tokens.
  TOKEN_ERROR, TOKEN_EOF
};
